#ifndef _MODELER_GLOBALS_H
#define _MODELER_GLOBALS_H

#ifndef M_PI
#define M_PI 3.141592653589793238462643383279502
#endif

// This is a list of the controls for the SampleModel
// We'll use these constants to access the values 
// of the controls from the user interface.
enum SampleModelControls
{
	XPOS, YPOS, ZPOS, ROTATE_ALL,
	LIGHT0_ENABLE, LIGHT1_ENABLE,
	LIGHTX_0, LIGHTY_0, LIGHTZ_0,
	LIGHTX_1, LIGHTY_1, LIGHTZ_1,
	LIGHT_INTENSITY,
	LOD, INSTANCES, MOODS,
	NECK_PITCH, NECK_YAW, NECK_ROLL,
	HEAD_PITCH, HEAD_YAW, HEAD_ROLL,
	LEFT_FORELIMP_1, RIGHT_FORELIMP_1, LEFT_REARLIMP_1, RIGHT_REARLIMP_1, // the four thighs
	LEFT_FORELIMP_1_YAW, RIGHT_FORELIMP_1_YAW, LEFT_REARLIMP_1_YAW, RIGHT_REARLIMP_1_YAW,
	LEFT_FORELIMP_2, RIGHT_FORELIMP_2, LEFT_REARLIMP_2, RIGHT_REARLIMP_2,
	LEFT_FORELIMP_2_YAW, RIGHT_FORELIMP_2_YAW, LEFT_REARLIMP_2_YAW, RIGHT_REARLIMP_2_YAW,
	LEFT_FORELIMP_3, RIGHT_FORELIMP_3, LEFT_REARLIMP_3, RIGHT_REARLIMP_3,
	LEFT_FORELIMP_3_YAW, RIGHT_FORELIMP_3_YAW, LEFT_REARLIMP_3_YAW, RIGHT_REARLIMP_3_YAW,
	TAIL_PITCH, TAIL_YAW,
	LIMP_FOLDING,
	L_SYSTEM_ENABLE, L_SYSTEM_ANGLE, L_SYSTEM_BRANCH_LENGTH,
	CURVE_ENABLE,CURVE_ROTATION,
	POINT_X1, POINT_Y1, POINT_Z1,
	POINT_X2, POINT_Y2, POINT_Z2,
	POINT_X3, POINT_Y3, POINT_Z3,
	POINT_X4, POINT_Y4, POINT_Z4,
	POLYGON_TORUS, PRIMITIVE_TORUS,
	TORUS_RING_LR, TORUS_RING_SR, TORUS_TUBE_LR, TORUS_TUBE_SR,
	TORUS_PX, TORUS_PY, TORUS_PZ, TORUS_RX, TORUS_RY, TORUS_RZ,
	TORUS_FLOWER, TORUS_PETAL,
	DRAW_NURBS,
	NUMCONTROLS
};

// Colors
#define COLOR_RED		1.0f, 0.0f, 0.0f
#define COLOR_GREEN		0.0f, 1.0f, 0.0f
#define COLOR_BLUE		0.0f, 0.0f, 1.0f

// We'll be getting the instance of the application a lot; 
// might as well have it as a macro.
#define VAL(x) (ModelerApplication::Instance()->GetControlValue(x))

#endif